const commitments = ["Move twice", "Drink your water", "Hit your step target", "Read and reset"];

export default function HomePage() {
  return <main>
    <nav className="nav shell"><a className="brand" href="#top" aria-label="ShipShape 90 home"><span className="mark">S90</span><span>ShipShape 90</span></a><div className="navLinks"><a href="#how">How it works</a><a href="#features">Features</a><a className="navCta" href="#waitlist">Get the app</a></div></nav>
    <section id="top" className="hero shell"><div className="heroCopy"><p className="eyebrow">ACCOUNTABILITY, MADE VISIBLE</p><h1>Turn your commitments into a scoreboard.</h1><p className="lede">Join a challenge or build your own. Check off the work, earn every point, and see exactly where you stand—one honest day at a time.</p><div className="heroActions"><a className="button primary" href="#waitlist">Join the early list</a><a className="button secondary" href="#how">See how it works</a></div><p className="fine">Built for iPhone and Android. Web access included.</p></div><div className="phone" aria-label="Preview of the ShipShape Today screen"><div className="phoneTop"><span>90 STRONG · DAY 37</span><strong>12 day streak</strong></div><h2>Own today.</h2><div className="scoreCard"><div className="ring"><span>40%</span></div><div><small>TODAY'S SCORE</small><strong>2 / 10</strong><p>3 tasks left to unlock the perfect-day bonus.</p></div></div><div className="tasks">{commitments.map((task, index) => <div className="task" key={task}><span className={index < 2 ? "check checked" : "check"}>{index < 2 ? "✓" : ""}</span><span>{task}</span><b>{index < 2 ? "+1" : "1 pt"}</b></div>)}</div></div></section>
    <section className="proof"><div className="shell proofGrid"><div><strong>90</strong><span>days by default</span></div><div><strong>1</strong><span>clear daily plan</span></div><div><strong>0</strong><span>mystery scoring rules</span></div></div></section>
    <section id="how" className="section shell"><p className="eyebrow">THE LOOP</p><h2>Simple enough for today.<br/>Flexible enough for your rules.</h2><div className="steps"><article><span>01</span><h3>Choose the challenge</h3><p>Browse public challenges, enter an invite code, or create your own private competition.</p></article><article><span>02</span><h3>Do the work</h3><p>Your Today view shows only what is scheduled now, including proof and quantity requirements.</p></article><article><span>03</span><h3>Earn your place</h3><p>Points come from an append-only ledger, so bonuses, penalties, and final standings stay explainable.</p></article></div></section>
    <section id="features" className="section warm"><div className="shell split"><div><p className="eyebrow">BUILT FOR REAL ACCOUNTABILITY</p><h2>Competition without the chaos.</h2><p className="lede small">Creators define dates, tasks, proof, scoring, and winner conditions before the challenge begins. Participants always know what counts.</p></div><ul className="featureList"><li><b>Daily clarity</b><span>Progress, remaining work, streak, and score in one view.</span></li><li><b>Private by design</b><span>Invite-only groups and private evidence are first-class.</span></li><li><b>Fair results</b><span>Deterministic scoring, ordered tie-breakers, and frozen final standings.</span></li><li><b>Your challenge</b><span>Fitness is the flagship—not the limitation.</span></li></ul></div></section>
    <section id="waitlist" className="cta shell"><p className="eyebrow">SHIPSHAPE90.COM</p><h2>Ready to make the next 90 days count?</h2><p>Mobile product development is underway. Join the launch list for iPhone and Android access.</p><form><label className="srOnly" htmlFor="email">Email address</label><input id="email" type="email" placeholder="you@example.com" required/><button type="submit">Keep me posted</button></form><small>No spam. Just meaningful product updates.</small></section>
    <footer className="footer shell"><span>© 2026 ShipShape 90</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/support">Support</a></div></footer>
  </main>;
}
