import { Icon, theme } from "@shipshape/ui-mobile";
import { StyleSheet, Text, View } from "react-native";
import type { ChallengeLeaderboardEntry } from "../features/leaderboard/leaderboardRepository";

const initialsFor = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "SS";

function PodiumPlayer({ entry, place }: { entry: ChallengeLeaderboardEntry; place: 1 | 2 | 3 }) {
  return <View style={[styles.podiumPlayer, place === 1 && styles.podiumWinner]}>
    <View style={[styles.crown, place === 1 && styles.crownWinner]}>{place === 1 ? <Icon name="trophy" size={19} color={theme.colors.text}/> : <Text style={styles.placeText}>{place}</Text>}</View>
    <View style={[styles.podiumAvatar, place === 1 && styles.podiumAvatarWinner]}><Text style={styles.podiumInitials}>{initialsFor(entry.displayName)}</Text></View>
    <Text numberOfLines={1} style={styles.podiumName}>{entry.isCurrentUser ? "YOU" : entry.displayName.split(" ")[0]}</Text>
    <Text style={styles.podiumScore}>{entry.totalScore}</Text><Text style={styles.podiumXp}>POINTS</Text>
    {entry.bonusPoints > 0 ? <Text style={styles.bonus}>+{entry.bonusPoints} BODY</Text> : null}
  </View>;
}

export function GameLeaderboard({ entries }: { entries: ChallengeLeaderboardEntry[] }) {
  const first = entries[0]; const second = entries[1]; const third = entries[2];
  const rest = entries.slice(3);
  return <View style={styles.wrap}>
    {entries.length ? <View style={styles.podium}>{second ? <PodiumPlayer entry={second} place={2}/> : <View style={styles.podiumSpacer}/>}{first ? <PodiumPlayer entry={first} place={1}/> : null}{third ? <PodiumPlayer entry={third} place={3}/> : <View style={styles.podiumSpacer}/>}</View> : <View style={styles.empty}><Text style={styles.emptyTitle}>The board is waiting.</Text><Text style={styles.emptyBody}>Submit the first task to claim the top spot.</Text></View>}
    {rest.length ? <View style={styles.chase}><View style={styles.chaseHead}><Text style={styles.chaseTitle}>THE CHASE</Text><Text style={styles.chaseMeta}>LIVE</Text></View>{rest.map((entry, index) => { const ahead = entries[index + 2]; const gap = ahead ? Math.max(0, Number((ahead.totalScore - entry.totalScore).toFixed(2))) : 0; return <View key={entry.memberId} style={[styles.chaseRow, entry.isCurrentUser && styles.chaseRowYou]}><View style={[styles.rank, entry.isCurrentUser && styles.rankYou]}><Text style={[styles.rankText, entry.isCurrentUser && styles.rankTextYou]}>{entry.rank}</Text></View><View style={styles.avatar}><Text style={styles.initials}>{initialsFor(entry.displayName)}</Text></View><View style={styles.copy}><View style={styles.nameRow}><Text style={styles.name}>{entry.displayName}</Text>{entry.isCurrentUser ? <Text style={styles.youBadge}>YOU</Text> : null}</View><Text style={styles.gap}>{gap > 0 ? `${gap} points to #${entry.rank - 1}` : `${entry.perfectDays} perfect days`}</Text></View><View style={styles.scoreBox}><Text style={styles.score}>{entry.totalScore}</Text><Text style={styles.xp}>POINTS</Text></View></View>; })}</View> : null}
  </View>;
}

const styles = StyleSheet.create({
  wrap:{gap:18},podium:{minHeight:245,flexDirection:"row",alignItems:"flex-end",justifyContent:"center",gap:8,paddingHorizontal:10,paddingTop:34,paddingBottom:14,borderRadius:26,borderWidth:1,borderColor:theme.colors.accent,backgroundColor:theme.colors.accentSoft},podiumSpacer:{flex:1},podiumPlayer:{flex:1,minWidth:0,alignItems:"center",paddingHorizontal:5,paddingTop:28,paddingBottom:14,borderRadius:18,borderWidth:1,borderColor:theme.colors.border,backgroundColor:theme.colors.surface},podiumWinner:{paddingTop:20,paddingBottom:23,borderWidth:2,borderColor:theme.colors.brand,backgroundColor:theme.colors.brandSoft,shadowColor:theme.colors.brand,shadowOpacity:.14,shadowRadius:12,shadowOffset:{width:0,height:6},elevation:3},crown:{position:"absolute",top:-16,width:34,height:34,borderRadius:17,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:theme.colors.accent,backgroundColor:theme.colors.surface},crownWinner:{width:40,height:40,top:-22,borderRadius:20,borderColor:theme.colors.accent,backgroundColor:theme.colors.accent},placeText:{color:theme.colors.text,fontFamily:theme.type.body,fontWeight:"900",fontSize:13},podiumAvatar:{width:48,height:48,borderRadius:24,alignItems:"center",justifyContent:"center",backgroundColor:theme.colors.accentSoft,borderWidth:2,borderColor:theme.colors.accent},podiumAvatarWinner:{width:58,height:58,borderRadius:29,backgroundColor:theme.colors.brand,borderColor:theme.colors.brandStrong},podiumInitials:{color:theme.colors.text,fontFamily:theme.type.body,fontWeight:"900",fontSize:14},podiumName:{maxWidth:"100%",marginTop:9,color:theme.colors.text,fontFamily:theme.type.body,fontWeight:"800",fontSize:12},podiumScore:{marginTop:4,color:theme.colors.text,fontFamily:theme.type.display,fontSize:31,lineHeight:33},podiumXp:{color:theme.colors.textMuted,fontFamily:theme.type.body,fontWeight:"800",fontSize:7,letterSpacing:1},bonus:{marginTop:6,paddingHorizontal:7,paddingVertical:4,borderRadius:999,overflow:"hidden",color:theme.colors.text,backgroundColor:theme.colors.accent,fontFamily:theme.type.body,fontWeight:"900",fontSize:7,letterSpacing:.5},
  chase:{gap:9},chaseHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:2},chaseTitle:{color:theme.colors.text,fontFamily:theme.type.body,fontWeight:"900",fontSize:11,letterSpacing:1.2},chaseMeta:{color:theme.colors.brandStrong,fontFamily:theme.type.body,fontWeight:"900",fontSize:8,letterSpacing:1},chaseRow:{minHeight:72,flexDirection:"row",alignItems:"center",gap:10,padding:11,borderRadius:17,borderWidth:1,borderColor:theme.colors.border,backgroundColor:theme.colors.surface},chaseRowYou:{borderWidth:2,borderColor:theme.colors.brand,backgroundColor:theme.colors.brandSoft},rank:{width:34,height:34,borderRadius:12,alignItems:"center",justifyContent:"center",backgroundColor:theme.colors.subtle},rankYou:{backgroundColor:theme.colors.brand},rankText:{color:theme.colors.text,fontFamily:theme.type.display,fontSize:22},rankTextYou:{color:"#fff"},avatar:{width:40,height:40,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:theme.colors.accentSoft},initials:{color:theme.colors.text,fontFamily:theme.type.body,fontWeight:"900",fontSize:11},copy:{flex:1},nameRow:{flexDirection:"row",alignItems:"center",gap:6},name:{flexShrink:1,color:theme.colors.text,fontFamily:theme.type.body,fontWeight:"800",fontSize:13},youBadge:{paddingHorizontal:6,paddingVertical:2,borderRadius:999,overflow:"hidden",color:"#fff",backgroundColor:theme.colors.brand,fontFamily:theme.type.body,fontWeight:"900",fontSize:7},gap:{marginTop:2,color:theme.colors.textMuted,fontFamily:theme.type.body,fontSize:10},scoreBox:{alignItems:"flex-end"},score:{color:theme.colors.text,fontFamily:theme.type.display,fontSize:27,lineHeight:29},xp:{color:theme.colors.textMuted,fontFamily:theme.type.body,fontWeight:"900",fontSize:7,letterSpacing:1},empty:{alignItems:"center",padding:28,borderRadius:22,backgroundColor:theme.colors.subtle,gap:4},emptyTitle:{color:theme.colors.text,fontFamily:theme.type.body,fontWeight:"900",fontSize:16},emptyBody:{color:theme.colors.textSecondary,fontFamily:theme.type.body,fontSize:12},
});
