import type { Metadata } from "next";
import { LegalShell } from "../legal-shell";

export const metadata: Metadata = { title: "Privacy Policy", description: "How ShipShape 90 collects, uses, protects, and deletes personal information." };

export default function PrivacyPage() {
  return <LegalShell eyebrow="PRIVACY POLICY" title="Your work is personal." intro="This policy explains what ShipShape 90 collects, why we use it, and the choices you have.">
    <section><h2>Information we collect</h2><p>We collect the information you provide when creating and using an account, including your email address, name, username, profile photo, challenge participation, task submissions, scores, progress logs, optional weight and body-fat measurements, optional progress photos, and support messages.</p><p>We also receive basic device and service information needed to operate the app, such as notification tokens, app version, device platform, timestamps, network requests, and security logs. If you use Sign in with Apple or Google, that provider gives us an account identifier and any name or email information you choose to share.</p></section>
    <section><h2>How we use information</h2><p>We use this information to authenticate you, operate challenges, calculate scores, show progress and rankings, deliver notifications, prevent misuse, troubleshoot problems, provide support, and improve ShipShape 90.</p></section>
    <section><h2>Visibility inside challenges</h2><p>Your display name, username, profile photo, score, rank, and relevant challenge activity may be visible to people participating in the same challenge. Progress photos, body measurements, and private evidence are not made public unless a feature clearly asks you to share them and you choose to do so.</p></section>
    <section><h2>Analytics and diagnostics</h2><p>We use PostHog to understand product interactions and basic app lifecycle events, and Sentry to diagnose crashes and technical errors. These services may receive a private internal profile identifier, sanitized screen names, device platform, app version, and technical error details. We do not send them your email, name, username, notification content, challenge invite codes, body measurements, private notes, task text, or photos. Session replay, screenshots, and view-hierarchy capture are disabled.</p></section>
    <section><h2>Service providers</h2><p>We use service providers to run ShipShape 90, including Supabase for authentication, database, storage, and server functions; Expo for mobile builds and push delivery; Ably for realtime updates; PostHog for product analytics; Sentry for crash diagnostics; Vercel for the website; Apple for iOS distribution and optional Apple sign-in; and Google for optional Google sign-in. They process information only to provide their services to us and under their own security and privacy commitments.</p><p>We do not sell your personal information, use sensitive fitness information for advertising, or track you across other companies&apos; apps and websites.</p></section>
    <section><h2>Retention and deletion</h2><p>We keep account information while your account is active and as reasonably necessary to operate, secure, and comply with legal obligations. You can permanently delete your account in the app from Profile → Delete account. Deletion removes your login, profile, personal media, progress logs, notifications, and personal participation records. Challenges you created may remain without your identity so other members can retain their own results.</p><p>Backup systems and security logs may retain limited information for a short period before routine deletion. We may retain information when required by law, to resolve disputes, or to prevent fraud and abuse.</p></section>
    <section><h2>Your choices</h2><p>You can update your name, username, and profile photo in the app. You can pause push delivery in Notification Settings or change system-level permissions in your device settings. You may request access, correction, or deletion assistance by contacting us.</p></section>
    <section><h2>Security and age</h2><p>We use technical and organizational safeguards designed to protect your information, but no online service can guarantee absolute security. ShipShape 90 is not directed to children under 13, and we do not knowingly collect personal information from children under 13.</p></section>
    <section><h2>Changes and contact</h2><p>We may update this policy as the product changes. Material updates will be posted here with a revised effective date. Questions or privacy requests can be sent to <a href="mailto:support@shipshape90.com">support@shipshape90.com</a>.</p></section>
  </LegalShell>;
}
