import { Pressable, StyleSheet, Text, View } from "react-native";
import Svg, { Path } from "react-native-svg";
import { Icon } from "./Icon";
import { theme } from "./theme";

export interface ChallengeCardProps { title: string; status: "active" | "upcoming" | "complete"; meta: string; members: string; progress: number; isPrivate?: boolean; isSaved?: boolean; isQueued?: boolean; onToggleSaved?: () => void; onPress?: () => void; }

export function ChallengeCard({ title, status, meta, members, progress, isPrivate, isSaved = false, isQueued = false, onToggleSaved, onPress }: ChallengeCardProps) {
  const label = isQueued && status === "upcoming" ? "QUEUED" : status === "active" ? "ACTIVE" : status === "upcoming" ? "STARTS SOON" : "COMPLETE";
  return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.header}><View style={[styles.pill, status === "upcoming" && styles.pillUpcoming, isQueued && styles.pillQueued, status === "complete" && styles.pillComplete]}><Text style={[styles.pillText, status === "upcoming" && styles.pillTextDark, isQueued && styles.pillTextQueued, status === "complete" && styles.pillTextComplete]}>{label}</Text></View><View style={styles.headerActions}>{isPrivate ? <Text style={styles.private}>PRIVATE</Text> : null}{onToggleSaved ? <Pressable accessibilityRole="button" accessibilityLabel={isSaved ? `Remove ${title} from saved challenges` : `Save ${title}`} accessibilityState={{ selected: isSaved }} hitSlop={8} onPress={(event) => { event.stopPropagation(); onToggleSaved(); }} style={({ pressed }) => [styles.saveButton, isSaved && styles.saveButtonSelected, pressed && styles.saveButtonPressed]}><Icon name="heart" size={19} strokeWidth={2} color={isSaved ? theme.colors.brandStrong : theme.colors.textSecondary} filled={isSaved} /></Pressable> : null}</View></View><Text style={styles.title}>{title}</Text><Text style={styles.meta}>{meta}</Text><View style={styles.track}><View style={[styles.progress, { width: `${Math.min(100, Math.max(0, progress))}%` }, status === "complete" && styles.progressComplete]} /></View><View style={styles.footer}><Text style={styles.members}>{members}</Text><Svg width={20} height={20} viewBox="0 0 24 24"><Path d="m9 6 6 6-6 6" fill="none" stroke={theme.colors.textSecondary} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" /></Svg></View></Pressable>;
}

const styles = StyleSheet.create({ card: { minHeight: 196, padding: 16, gap: 10, borderRadius: theme.radius.xl, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface }, pressed: { transform: [{ scale: 0.99 }], opacity: .85 }, header: { minHeight: 40, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerActions: { flexDirection: "row", alignItems: "center", gap: 8 }, saveButton: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface }, saveButtonSelected: { borderColor: theme.colors.brand, backgroundColor: theme.colors.brandSoft }, saveButtonPressed: { transform: [{ scale: 0.92 }], opacity: .8 }, pill: { borderRadius: 999, backgroundColor: theme.colors.brand, paddingHorizontal: 9, paddingVertical: 5 }, pillUpcoming: { backgroundColor: theme.colors.accent }, pillQueued: { backgroundColor: theme.colors.brandSoft }, pillComplete: { backgroundColor: theme.colors.successSoft }, pillText: { color: "#fff", fontFamily: theme.type.body, fontSize: 10, fontWeight: "800", letterSpacing: 1 }, pillTextDark: { color: theme.colors.text }, pillTextQueued: { color: theme.colors.brandStrong }, pillTextComplete: { color: theme.colors.success }, private: { color: theme.colors.textMuted, fontFamily: theme.type.body, fontSize: 10, fontWeight: "700", letterSpacing: 1 }, title: { color: theme.colors.text, fontFamily: theme.type.body, fontSize: 24, lineHeight: 30, fontWeight: "700" }, meta: { color: theme.colors.textSecondary, fontFamily: theme.type.body, fontSize: 14 }, track: { height: 8, overflow: "hidden", borderRadius: 999, backgroundColor: theme.colors.border }, progress: { height: 8, borderRadius: 999, backgroundColor: theme.colors.brand }, progressComplete: { backgroundColor: theme.colors.success }, footer: { minHeight: 24, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, members: { color: theme.colors.textSecondary, fontFamily: theme.type.body, fontWeight: "700", fontSize: 12, letterSpacing: .8 } });
