import type { Metadata } from "next";
import { LegalShell } from "../legal-shell";

export const metadata: Metadata = { title: "Terms of Use", description: "The terms that govern use of ShipShape 90." };

export default function TermsPage() {
  return <LegalShell eyebrow="TERMS OF USE" title="Compete honestly." intro="These terms are the shared rules for using ShipShape 90 and participating in challenges.">
    <section><h2>Using ShipShape 90</h2><p>You must be at least 13 years old and legally able to agree to these terms. You are responsible for your account, the accuracy of information you submit, and activity performed through your account. Do not share access codes or use another person’s account without permission.</p></section>
    <section><h2>Challenges, scoring, and forfeiture</h2><p>Challenge participation uses the honor system. You check off your own completed tasks, and ShipShape 90 does not require proof unless a future feature clearly says otherwise. You agree to report completion honestly.</p><p>Challenge rules, dates, tasks, scoring, winning conditions, and prizes are shown before participation. ShipShape scoring is calculated from recorded task submissions, bonuses, and penalties. Realtime displays can change as new activity arrives or corrections are processed.</p><p>You may participate in one active challenge at a time. Leaving or switching away from an active challenge forfeits prize eligibility and prevents rejoining that challenge. Joining late does not allow backfilling days before your membership began. Challenge days are evaluated using each participant’s local challenge timezone.</p></section>
    <section><h2>Hosts and prizes</h2><p>Challenge hosts are responsible for the challenges they create, including lawful rules, participant decisions, prize descriptions, prize funding, winner verification, and prize delivery. ShipShape 90 provides tracking and scoring tools but is not the sponsor, escrow provider, or guarantor of user-created prizes unless a challenge expressly states otherwise.</p></section>
    <section><h2>Health and safety</h2><p>ShipShape 90 is an accountability product, not medical care. Content in the app is not medical, nutritional, or fitness advice. Choose tasks appropriate for your ability, consult a qualified professional when needed, and stop activity if you experience pain, dizziness, unusual shortness of breath, or another concerning symptom. Do not use the app for emergencies.</p></section>
    <section><h2>Your content</h2><p>You retain ownership of content you upload. You grant ShipShape 90 a limited license to store, process, display, and transmit that content only as needed to operate and improve the service. You must have the right to upload your content and must not submit unlawful, harmful, deceptive, infringing, or abusive material.</p></section>
    <section><h2>Fair play</h2><p>Do not falsify task completion, manipulate scoring, harass participants, scrape private information, disrupt the service, evade access controls, or use ShipShape 90 for illegal activity. We may remove content, limit access, disqualify results, or suspend accounts when reasonably necessary to protect participants and the service.</p></section>
    <section><h2>Availability and changes</h2><p>We work to keep ShipShape 90 reliable, but the service may be interrupted, changed, or discontinued. We may correct scoring or data errors when needed to preserve accurate results. Features may evolve as the product develops.</p></section>
    <section><h2>Disclaimers and responsibility</h2><p>To the fullest extent permitted by law, ShipShape 90 is provided “as is” without warranties of uninterrupted availability, fitness results, prize delivery by a user-created challenge host, or any particular outcome. You are responsible for your decisions, activities, and interactions with other participants.</p></section>
    <section><h2>Account ending and contact</h2><p>You may delete your account in the app. We may suspend or terminate access for serious or repeated violations of these terms. Provisions that by their nature should survive termination—including ownership, disclaimers, and responsibility—continue to apply.</p><p>Questions about these terms can be sent to <a href="mailto:support@shipshape90.com">support@shipshape90.com</a>.</p></section>
  </LegalShell>;
}
